version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      all-deps:
        patterns:
          - "*"
  - package-ecosystem: "uv"
    directory: "/"
    target-branch: "beta"
    schedule:
      interval: "daily"
    groups:
      all-deps:
        patterns:
          - "*"
  - package-ecosystem: "uv"
    directory: "/"
    target-branch: "httpx"
    schedule:
      interval: "daily"
    groups:
      all-deps:
        patterns:
          - "*"