repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff-format
        exclude: ^(meraki/(aio/api|api/batch|api)/|notebooks/|generator/generate_snippets\.py)
      - id: ruff
        args: [--fix]
        exclude: ^(meraki/(aio/api|api/batch|api)/|notebooks/|generator/generate_snippets\.py)
